apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cw9s6fpym-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cw9s6fpym-java-quarkus-gitops